# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-12-05 16:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lib', '0003_auto_20171205_2228'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='Title', max_length=200, null=True, verbose_name='Title')),
            ],
        ),
    ]
