# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-12-05 17:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lib', '0006_book_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='level',
            field=models.CharField(blank=True, help_text='Title', max_length=200, null=True, verbose_name='Level'),
        ),
    ]
