# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-12-05 18:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lib', '0009_comment_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='image',
            field=models.ImageField(default='images/books/None/no-img.jpg', upload_to='images/books/'),
        ),
    ]
