# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-12-05 18:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lib', '0010_book_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='location',
            field=models.ManyToManyField(blank=True, null=True, related_name='books', to='lib.Location'),
        ),
    ]
