# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-03-25 13:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lib', '0014_auto_20171206_2312'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='booker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='booked', to=settings.AUTH_USER_MODEL),
        ),
    ]
