# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-06-03 13:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lib', '0015_book_booker'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='rating',
            field=models.ManyToManyField(related_name='rated', to=settings.AUTH_USER_MODEL),
        ),
    ]
